version: "3.9"

services:

  postgres:
    container_name: "postgresql"
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank
    ports:
      - "5432:5432"